server:
  port: 8087
  max-http-header-size: 102400
  compression:
    enabled: true
    min-response-size: 2048
    mime-types: application/json,application/xml,text/html,text/xml,text/plain
swagger:
  enable: true
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
#    url: jdbc:mysql://192.168.1.77:3306/salary?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull
#    username: root
#    password: 123
#    url: jdbc:mysql://49.233.81.91:3306/salary_prod?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull
#    username: root
#    password: myroot123
    url: jdbc:mysql://112.35.152.110:3306/salary_prod?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull
    username: root
    password: TYZQ123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      initial-size: 10 #连接池初始化大小
      min-idle: 10 #最小空闲连接数
      max-active: 500 #最大连接数
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #不统计这些请求数据
      stat-view-servlet: #访问监控网页的登录用户名和密码
        login-username: druid
        login-password: druid
  redis:
    database: 6
    host: 112.35.152.110
    port: 6379
    password: myroot
    jedis:
      pool:
        max-active: 10
        max-wait: 6000ms
        max-idle: 8
        min-idle: 5
#mybatis
mybatis-plus:
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath*:com/**/xml/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#开启SpringBoot Admin的监控
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
# 文件资源映射
file:
  relativePath: /uploadfiles/**
  physicalPath: /home/SALARY/
# 对外接口秘钥
keygen:
  querySalary: QS21FCA75610B922B7B2609B40E3H32W
  queryUser: QU83EG75610B922B7B2609B40E3S03G
# 分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql